### ISSUE TITLE
Keeping it updated

### ISSUE THREAD

**Issue by zodern** [yasaricli/blaze#1]
I have been waiting for someone to do this! Did you have to manually pull the files out of Meteor? Is there a way you can automate it so this stays up to date with the version in Meteor?

**Comment by yasaricli** [comment]
Have any ideas @zodern ?

**Comment by zodern** [comment]
You could use a bash or nodejs script to automate it. And once [this](https://forums.meteor.com/t/get-notified-when-your-package-breaks-on-new-meteor-versions/12529) gets done, you can have the CI automatically do it after checking the meteor version is not a release candidate.

Though with the [future of blaze](https://forums.meteor.com/t/next-steps-on-blaze-and-the-view-layer/13561/113) I don't know if it is worth doing it.

**Comment by yasaricli** [comment]
yasaricli ~/Desktop/Projects/blaze (master)*$ ./blaze --server
    Created a new Meteor app in '.blaze'.

    To run your new app:
      cd .blaze
      meteor

    If you are new to Meteor, try some of the learning resources here:
      https://www.meteor.com/learn


    blaze-tools: Compile-time tools for Blaze
    html-tools: Standards-compliant HTML tools
    spacebars-compiler: Compiler for Spacebars template language
    [[[[[ ~/Desktop/Projects/blaze/.blaze ]]]]]

    => Started proxy.
    => Started MongoDB.
    => Started your app.

    => App running at: http://localhost:3000/

**Comment by yasaricli** [comment]
hey; @zodern 

#### start current meteor server:

```
./blaze --server
```

#### and download current version scripts.

```
./blaze --download
```

updated **src/*.js** all blaze files.

also the current version at the moment **bower 0.0.2**

**Comment by zodern** [comment]
That's great! I will try using this in a small app next week.

**Comment by yasaricli** [comment]
@zodern ask me any problems and you can also help.
